name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      dynamodb: amazon/dynamodb-local
      ports:
        - 8000:8000
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.x
          elixir-version: 1.10.x
      - name: cache mix.deps
        id: cache-deps
        uses: actions/cache@v2
        with: |
          deps
          _build
        key: v1-surge-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: v1-surge-
      - name: execute mix deps.get if cache miss happened
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
